import { FC } from "react"
import { Sidebar } from "../sidebar"
import Head from "next/head"
import { useRouter } from 'next/router'
import { Header } from "../header"


interface Props {
    children: JSX.Element | JSX.Element[]
    title?: string
}

export const Layout: FC<Props> = ({ children, title }) => {

    const router = useRouter();
    return (
        <>
            <Head>
                <title>{title}</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            {/*  "use /direction" for router.pathname */}
            {router.pathname === '/login' || router.pathname === '/create-account' ?
                <div className="bg-gray-800 min-h-screen flex flex-col justify-center">
                    <div className="animate">
                        {children}
                    </div>
                </div>
                : <div className="bg-gray-800 min-h-screen">
                    <div className="sm:flex min-h-screen">
                        <Sidebar />
                        <main className="bg-gray-800 sm:w-2/3 xl:w-4/5 sm:min-h-screen p-5">
                            <Header/>
                            {children}
                        </main>
                    </div>
                </div>
            }

        </>
    )
}

